mqtt_bridge_node:
  ros__parameters:
    mqtt:
      tls:
        ca_certs: /etc/ssl/certs/Root_CA.pem
        certfile: /etc/ssl/certs/Client.pem
        keyfile: /etc/ssl/private/Client.key
        tls_insecure: true